### ISSUE TITLE
Editor doesn't show up. 404 error

### ISSUE THREAD

**Issue by arturaum** [chiqui3d/strapi-tinymce#1]
I followed your instructions, but this editor still doesn't work for me.

Debug info:
`GET /tinymce/js/tinymce/tinymce.min.js (2 ms) 404`

**Comment by arturaum** [comment]
> In addition, it downloads the Tinymce prod files from https://www.tiny.cloud/get-tiny/self-hosted/ and adds them to the public folder. This is because if you don't get a message inside the editor that you need a cloud api key, and we want to use it for self-hosted.

Ok, I download files manualy and it works now ;)

**Comment by g-u-x** [comment]
+1 
Sorry, same problem here, I added the production files to the public folder (tried keeping the same folder structure from the downloaded files from Tiny site and even to move them to the root of the public folder, and after several attempts the 404 error is still there.
Am I missing something?

strapi v3.4.5
@tinymce/tinymce-react v^3.10.1
node v10.23.2

Production files
https://imgur.com/xZdWhuS

Editor not showing
https://imgur.com/PH52D2J

**Comment by arturaum** [comment]
@g-u-x I simply unziped "tinymce" to "public" folder and it began to work

**Comment by g-u-x** [comment]
@arturaum working great by doing exactly that, thanks!
