### ISSUE TITLE
media upload doesn't show anything

### ISSUE THREAD

**Issue by nhd2106** [chiqui3d/strapi-tinymce#2]
Hi There,
have you ever got this issue after installing a new editor?
thanks for reading.
![image](https://user-images.githubusercontent.com/45473614/94547589-a6f05a00-0279-11eb-96c2-8e42d6df9e7b.png)

**Comment by u007** [comment]
whats the logs on the strapi terminal?

**Comment by chiqui3d** [comment]
I am closing the issue, because I see that everything is working now. You can reopen it if necessary.
