### ISSUE TITLE
Editor is empty when re-opening object

### ISSUE THREAD

**Issue by alexndr-n** [chiqui3d/strapi-tinymce#6]
Hey, this is great and solved a problem really easy! I'm very thankful for that.

That being said, is there any way for the editor to load the text when you re-open it? Because even if you go in to change something else and save, the text camp will then be emptied.

**Comment by alenieto97** [comment]
Nevermind.

**Comment by alexndr-n** [comment]
Okay it doesn't delete the saved text, but also It would be nice if you knew a way for the stored text to show up when you re-open the editor.

**Comment by terenceng2010** [comment]
The editor should not be empty after saving the text. It should be repopulated with the html that has been stored. But I can't figure what went wrong.

**Comment by chiqui3d** [comment]
Thanks @blakej115, I will review. This never happened to me.

**Comment by bilalajanjua** [comment]
Hi @alenieto97 

Inside `extensions/content-manager/admin/src/components/WysiwygWithErrors/index.js`, Replace:

`<Editor name={name} onChange={onChange} value={value} />`

With: 

`<Editor name={name} onChange={onChange} value={value || ""} />`

Actually, the `value` prop is marked as required but WysiwygWithErrors component takes some time to get value in props. So a workaround is to give an empty string as default in case the value is currently null.

**Comment by bilalajanjua** [comment]
Hi @alenieto97 

The issue is that Tinymce is not updating the value prop.

A simple workaround is to remove the initialValue prop. So the correct `Tinymce.js` component would be: 

```js
// ...
<Tinymce
      value={value}
      tinymceScriptSrc={strapi.backendURL + "/tinymce/js/tinymce/tinymce.min.js"}
      init={{
        height: 500,
        menubar: false,
        convert_urls: false,
        relative_urls: true,
        remove_script_host: true,
        toolbar_mode: "wrap",
        plugins: [
          "advlist autolink lists link image charmap print preview anchor",
          "searchreplace visualblocks code fullscreen",
          "insertdatetime media table paste code help wordcount",
          "media codesample fullscreen",
          "hr visualchars imagetools emoticons",
        ],
        toolbar:
          "undo redo | formatselect forecolor backcolor | \
          bold italic underline strikethrough removeformat | \
          alignleft aligncenter alignright alignjustify | \
          outdent indent | numlist bullist | \
          table link anchor | image media codesample charmap emoticons | \
          fullscreen code",
      }}
      onEditorChange={(content, editor) => {
        onChange({ target: { name, value: content } });
      }}
    />
// ...
``` 

Also, from inside `extensions\content-manager\admin\src\components\WysiwygWithErrors\index.js`:

Replace:

`<Editor name={name} onChange={onChange} value={value} />`

With: 

`<Editor name={name} onChange={onChange} value={value || ""} />`

Make sure to run `yarn build` or `npm run build` after the changes.
