### ISSUE TITLE
Content doesn't load into editor if you visit page with editor, go to a different page, and then come back.

### ISSUE THREAD

**Issue by blakej115** [chiqui3d/strapi-tinymce#9]
I am wondering if my issue is a different issue than the one mentioned in #6 [Here is a video](https://youtu.be/gyv6nwetIOs) to make it clear. This still happens even after the fix from #8 is applied.

#7 was my proposed fix, although this fix seems hack-ish.

This does not seem to affect editors that are inside of a component.

**Comment by chiqui3d** [comment]
It works well for me, Build again before you run develop https://nimb.ws/BpS6Oq
